# print("Enter number 1")
# num1=input()
# print("Enter number 2")
# num2=input()
# sum=int(num1)+ int(num2)
# print("the sum is ",sum)
num1=input("Enter number 1 \n")
num2=input("Enter number 2 \n")
print(num1,num2)